extends:
  - stylelint-config-standard
plugins:
  - stylelint-prettier
rules:
  prettier/prettier: true
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
        - apply
        - variants
        - responsive
        - screen
  declaration-block-trailing-semicolon: null
  selector-class-pattern: null
